```{r}
correlate_metafor <- function(metafor_file, y1y2_file, y3_file){
  title <- gsub("/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/", "", metafor_file)
  title <- gsub(".RDS", "", title)
  title <- gsub("_", " ", title)
  print(title)
  
  metafor <- readRDS(metafor_file)
  y1y2 <- readRDS(y1y2_file)
  y3 <- readRDS(y3_file)
  
  # calculate z scores
  y1y2$Z <- abs(qnorm(y1y2$P.Value))*sign(y1y2$logFC)
  y3$Z <- abs(qnorm(y3$P.Value))*sign(y3$logFC)
  
  y1y2 <- y1y2[y1y2$gene %in% metafor$gene,]
  metafor <- metafor[order(metafor$gene),]
  y1y2 <- y1y2[order(y1y2$gene),]
  
  print("Y1Y2 and Metafor genes match:")
  print(identical(metafor$gene, y1y2$gene))
  
  print(nrow(y1y2))
  print("Y1Y2 Spearman:")
  print(cor(metafor$zval, y1y2$Z,method="spearman")[,1])
  print("Y1Y2 Pearson:")
  print(cor(metafor$zval, y1y2$Z,method="pearson")[,1])
  
  y3 <- y3[y3$gene %in% metafor$gene,]
  metafor <- metafor[order(metafor$gene),]
  y3 <- y3[order(y3$gene),]
  
  print("Y3 and Metafor genes match:")
  identical(metafor$gene, y3$gene)
  print(nrow(y3))
  
  print("Y3 Spearman:")
  print(cor(metafor$zval, y3$Z,method="spearman")[,1])
  print("Y3 Pearson:")
  print(cor(metafor$zval, y3$Z,method="pearson")[,1])
  cat("\n\n\n")
  
}
```



```{r}
# PTSD
correlate_metafor(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD/results_PTSD_CentralAmyg_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD/results_PTSD_CentralAmyg_PTSD.RDS")

correlate_metafor(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD/results_PTSD_DG_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD/results_PTSD_DG_PTSD.RDS")

correlate_metafor(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD/results_PTSD_mPFC_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD/results_PTSD_mPFC_PTSD.RDS")
# MDD
correlate_metafor(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/MDD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/MDD/results_MDD_CentralAmyg_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/MDD/results_MDD_CentralAmyg_MDD.RDS")

correlate_metafor(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/MDD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/MDD/results_MDD_DG_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/MDD/results_MDD_DG_MDD.RDS")

correlate_metafor(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/MDD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/MDD/results_MDD_mPFC_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/MDD/results_MDD_mPFC_MDD.RDS")
# PTSD + MDD
correlate_metafor(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_MDD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_MDD/results_PTSD+MDD_CentralAmyg_PTSD_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_MDD/results_PTSD+MDD_CentralAmyg_PTSD_MDD.RDS")

correlate_metafor(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_MDD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_MDD/results_PTSD+MDD_DG_PTSD_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_MDD/results_PTSD+MDD_DG_PTSD_MDD.RDS")

correlate_metafor(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_MDD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_MDD/results_PTSD+MDD_mPFC_PTSD_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_MDD/results_PTSD+MDD_mPFC_PTSD_MDD.RDS")
# PTSD vs MDD
correlate_metafor(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_vs_MDD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_vs_MDD/results_PTSD_vs_MDD_CentralAmyg_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_vs_MDD/results_PTSD_vs_MDD_CentralAmyg_PTSD.RDS")

correlate_metafor(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_vs_MDD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_vs_MDD/results_PTSD_vs_MDD_DG_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_vs_MDD/results_PTSD_vs_MDD_DG_PTSD.RDS")

correlate_metafor(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_vs_MDD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_vs_MDD/results_PTSD_vs_MDD_mPFC_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_vs_MDD/results_PTSD_vs_MDD_mPFC_PTSD.RDS")
```

```{r}
correlate_y1y2_y3 <- function(metafor_file, y1y2_file, y3_file){
  title <- gsub("/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/", "", metafor_file)
  title <- gsub(".RDS", "", title)
  title <- gsub("_", " ", title)
  print(title)
  
  y1y2 <- readRDS(y1y2_file)
  y3 <- readRDS(y3_file)
  
  # calculate z scores
  y1y2$Z <- abs(qnorm(y1y2$P.Value))*sign(y1y2$logFC)
  y3$Z <- abs(qnorm(y3$P.Value))*sign(y3$logFC)
  
  y1y2 <- y1y2[y1y2$gene %in% y3$gene,]
  y3 <- y3[y3$gene %in% y1y2$gene,]
  y1y2 <- y1y2[order(y1y2$gene),]
  y3 <- y3[order(y1y2$gene),]
  
  print("Y1Y2 and Y3 genes match:")
  print(identical(y1y2$gene, y3$gene))
  print(nrow(y1y2))
  
  print("Spearman:")
  print(cor(y1y2$Z, y3$Z,method="spearman")[,1])
  print("Pearson:")
  print(cor(y1y2$Z, y3$Z,method="pearson")[,1])
  
  cat("\n\n\n")
  
}

```

```{r}
# PTSD
correlate_y1y2_y3(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD/results_PTSD_CentralAmyg_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD/results_PTSD_CentralAmyg_PTSD.RDS")

correlate_y1y2_y3(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD/results_PTSD_DG_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD/results_PTSD_DG_PTSD.RDS")

correlate_y1y2_y3(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD/results_PTSD_mPFC_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD/results_PTSD_mPFC_PTSD.RDS")
# MDD
correlate_y1y2_y3(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/MDD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/MDD/results_MDD_CentralAmyg_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/MDD/results_MDD_CentralAmyg_MDD.RDS")

correlate_y1y2_y3(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/MDD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/MDD/results_MDD_DG_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/MDD/results_MDD_DG_MDD.RDS")

correlate_y1y2_y3(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/MDD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/MDD/results_MDD_mPFC_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/MDD/results_MDD_mPFC_MDD.RDS")
# PTSD + MDD
correlate_y1y2_y3(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_MDD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_MDD/results_PTSD+MDD_CentralAmyg_PTSD_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_MDD/results_PTSD+MDD_CentralAmyg_PTSD_MDD.RDS")

correlate_y1y2_y3(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_MDD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_MDD/results_PTSD+MDD_DG_PTSD_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_MDD/results_PTSD+MDD_DG_PTSD_MDD.RDS")

correlate_y1y2_y3(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_MDD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_MDD/results_PTSD+MDD_mPFC_PTSD_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_MDD/results_PTSD+MDD_mPFC_PTSD_MDD.RDS")
# PTSD vs MDD
correlate_y1y2_y3(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_vs_MDD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_vs_MDD/results_PTSD_vs_MDD_CentralAmyg_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_vs_MDD/results_PTSD_vs_MDD_CentralAmyg_PTSD.RDS")

correlate_y1y2_y3(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_vs_MDD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_vs_MDD/results_PTSD_vs_MDD_DG_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_vs_MDD/results_PTSD_vs_MDD_DG_PTSD.RDS")

correlate_y1y2_y3(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_vs_MDD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_vs_MDD/results_PTSD_vs_MDD_mPFC_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_vs_MDD/results_PTSD_vs_MDD_mPFC_PTSD.RDS")
```




```{r}
correlate_metafor_nom <- function(metafor_file, y1y2_file, y3_file){
  title <- gsub("/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/", "", metafor_file)
  title <- gsub(".RDS", "", title)
  title <- gsub("_", " ", title)
  print(title)
  
  metafor <- readRDS(metafor_file)
  metafor <- metafor[metafor$pval < 0.05,]
  
  y1y2 <- readRDS(y1y2_file)
  y1y2 <- y1y2[y1y2$P.Value < 0.05,]
  y3 <- readRDS(y3_file)
  y3 <- y3[y3$P.Value < 0.05,]
  
  # calculate z scores
  y1y2$Z <- abs(qnorm(y1y2$P.Value))*sign(y1y2$logFC)
  y3$Z <- abs(qnorm(y3$P.Value))*sign(y3$logFC)
  
  y1y2 <- y1y2[y1y2$gene %in% metafor$gene,]
  metafor_y1y2 <- metafor[metafor$gene %in% y1y2$gene,]
  
  metafor_y1y2 <- metafor_y1y2[order(metafor_y1y2$gene),]
  y1y2 <- y1y2[order(y1y2$gene),]
  
  print("Y1Y2 and Metafor genes match:")
  print(identical(metafor_y1y2$gene, y1y2$gene))
  
  print(nrow(y1y2))
  print("Y1Y2 Spearman:")
  print(cor(metafor_y1y2$zval, y1y2$Z,method="spearman")[,1])
  print("Y1Y2 Pearson:")
  print(cor(metafor_y1y2$zval, y1y2$Z,method="pearson")[,1])
  
  y3 <- y3[y3$gene %in% metafor$gene,]
  metafor_y3 <- metafor[metafor$gene %in% y3$gene,]
  
  metafor_y3 <- metafor_y3[order(metafor_y3$gene),]
  y3 <- y3[order(y3$gene),]
  
  print("Y3 and Metafor genes match:")
  identical(metafor_y3$gene, y3$gene)
  print(nrow(y3))
  
  print("Y3 Spearman:")
  print(cor(metafor_y3$zval, y3$Z,method="spearman")[,1])
  print("Y3 Pearson:")
  print(cor(metafor_y3$zval, y3$Z,method="pearson")[,1])
  cat("\n\n\n")
  
}
```

```{r}
# PTSD
correlate_metafor_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD/results_PTSD_CentralAmyg_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD/results_PTSD_CentralAmyg_PTSD.RDS")

correlate_metafor_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD/results_PTSD_DG_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD/results_PTSD_DG_PTSD.RDS")

correlate_metafor_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD/results_PTSD_mPFC_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD/results_PTSD_mPFC_PTSD.RDS")
# MDD
correlate_metafor_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/MDD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/MDD/results_MDD_CentralAmyg_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/MDD/results_MDD_CentralAmyg_MDD.RDS")

correlate_metafor_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/MDD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/MDD/results_MDD_DG_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/MDD/results_MDD_DG_MDD.RDS")

correlate_metafor_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/MDD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/MDD/results_MDD_mPFC_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/MDD/results_MDD_mPFC_MDD.RDS")
# PTSD + MDD
correlate_metafor_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_MDD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_MDD/results_PTSD+MDD_CentralAmyg_PTSD_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_MDD/results_PTSD+MDD_CentralAmyg_PTSD_MDD.RDS")

correlate_metafor_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_MDD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_MDD/results_PTSD+MDD_DG_PTSD_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_MDD/results_PTSD+MDD_DG_PTSD_MDD.RDS")

correlate_metafor_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_MDD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_MDD/results_PTSD+MDD_mPFC_PTSD_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_MDD/results_PTSD+MDD_mPFC_PTSD_MDD.RDS")
# PTSD vs MDD
correlate_metafor_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_vs_MDD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_vs_MDD/results_PTSD_vs_MDD_CentralAmyg_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_vs_MDD/results_PTSD_vs_MDD_CentralAmyg_PTSD.RDS")

correlate_metafor_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_vs_MDD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_vs_MDD/results_PTSD_vs_MDD_DG_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_vs_MDD/results_PTSD_vs_MDD_DG_PTSD.RDS")

correlate_metafor_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_vs_MDD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_vs_MDD/results_PTSD_vs_MDD_mPFC_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_vs_MDD/results_PTSD_vs_MDD_mPFC_PTSD.RDS")
```

```{r}
correlate_Y1Y2Y3_nom <- function(metafor_file, y1y2_file, y3_file){
  title <- gsub("/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/", "", metafor_file)
  title <- gsub(".RDS", "", title)
  title <- gsub("_", " ", title)
  print(title)
  
  y1y2 <- readRDS(y1y2_file)
  y1y2 <- y1y2[y1y2$P.Value < 0.05,]
  y3 <- readRDS(y3_file)
  y3 <- y3[y3$P.Value < 0.05,]
  
  # calculate z scores
  y1y2$Z <- abs(qnorm(y1y2$P.Value))*sign(y1y2$logFC)
  y3$Z <- abs(qnorm(y3$P.Value))*sign(y3$logFC)
  
  y1y2 <- y1y2[y1y2$gene %in% y3$gene,]
  y3 <- y3[y3$gene %in% y1y2$gene,]
  
  y1y2 <- y1y2[order(y1y2$gene),]
  y3 <- y3[order(y3$gene),]
  
  print("Y1Y2 and Y3 genes match:")
  print(identical(y1y2$gene, y3$gene))
  
  print(nrow(y1y2))
  print("Spearman:")
  print(cor(y1y2$Z, y3$Z,method="spearman")[,1])
  print("Pearson:")
  print(cor(y1y2$Z, y3$Z,method="pearson")[,1])
  
  cat("\n\n\n")
  
}



```

```{r}
# PTSD
correlate_Y1Y2Y3_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD/results_PTSD_CentralAmyg_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD/results_PTSD_CentralAmyg_PTSD.RDS")

correlate_Y1Y2Y3_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD/results_PTSD_DG_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD/results_PTSD_DG_PTSD.RDS")

correlate_Y1Y2Y3_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD/results_PTSD_mPFC_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD/results_PTSD_mPFC_PTSD.RDS")
# MDD
correlate_Y1Y2Y3_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/MDD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/MDD/results_MDD_CentralAmyg_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/MDD/results_MDD_CentralAmyg_MDD.RDS")

correlate_Y1Y2Y3_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/MDD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/MDD/results_MDD_DG_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/MDD/results_MDD_DG_MDD.RDS")

correlate_Y1Y2Y3_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/MDD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/MDD/results_MDD_mPFC_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/MDD/results_MDD_mPFC_MDD.RDS")
# PTSD + MDD
correlate_Y1Y2Y3_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_MDD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_MDD/results_PTSD+MDD_CentralAmyg_PTSD_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_MDD/results_PTSD+MDD_CentralAmyg_PTSD_MDD.RDS")

correlate_Y1Y2Y3_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_MDD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_MDD/results_PTSD+MDD_DG_PTSD_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_MDD/results_PTSD+MDD_DG_PTSD_MDD.RDS")

correlate_Y1Y2Y3_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_MDD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_MDD/results_PTSD+MDD_mPFC_PTSD_MDD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_MDD/results_PTSD+MDD_mPFC_PTSD_MDD.RDS")
# PTSD vs MDD
correlate_Y1Y2Y3_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_vs_MDD_CentralAmyg.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_vs_MDD/results_PTSD_vs_MDD_CentralAmyg_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_vs_MDD/results_PTSD_vs_MDD_CentralAmyg_PTSD.RDS")

correlate_Y1Y2Y3_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_vs_MDD_DG.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_vs_MDD/results_PTSD_vs_MDD_DG_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_vs_MDD/results_PTSD_vs_MDD_DG_PTSD.RDS")

correlate_Y1Y2Y3_nom(metafor_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/Metafor/RNA/Genes/PTSD_vs_MDD_mPFC.RDS",
                  y1y2_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y1Y2/PTSD_vs_MDD/results_PTSD_vs_MDD_mPFC_PTSD.RDS",
                  y3_file = "/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Limma_Results/Genes/FinalizedCovs_01_19_23/Y3/PTSD_vs_MDD/results_PTSD_vs_MDD_mPFC_PTSD.RDS")
```
















