---
output:
  pdf_document: default
  html_document: default
---
```{r}
library(variancePartition)

update_gene_names <- function(df){
  gene_map <- readRDS("/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/Bulk/RNA_Gene_Map.RDS")
  
  df$genes <- rownames(df)
  df <- merge(df, gene_map, by="genes", all.x=T)
  rownames(df) <- paste0(df$symbol, "_", df$genes)
  df <- df[ , -which(names(df) %in% c("genes","symbol"))]
  
  return(df)
}

ca <- readRDS("/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/VariancePartition/Genes/FinalizedCovs/VarPartFiles/Y1Y2/CentralAmyg_ctp7.RDS")
ca <- update_gene_names(ca)

dg <- readRDS("/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/VariancePartition/Genes/FinalizedCovs/VarPartFiles/Y1Y2/DG_ctp7.RDS")
dg <- update_gene_names(dg)


mpfc <- readRDS("/data/humgen/daskalakislab/dipietro/SciencePaper/Data/RNA/VariancePartition/Genes/FinalizedCovs/VarPartFiles/Y1Y2/mPFC_ctp7.RDS")
mpfc <- update_gene_names(mpfc)
```

```{r}

###############################
# Top Genes PTSD Central Amyg #
###############################
# MIR497HG (FDR-)
# LTBR (FDR+)
plotPercentBars(ca[startsWith(rownames(ca), "FKBP5"),])
plotPercentBars(ca[startsWith(rownames(ca), "MIR497HG"),])
plotPercentBars(ca[startsWith(rownames(ca), "LTBR"),])

```

```{r}

###############################
# Top Genes MDD Central Amyg #
###############################
# PDLIM4 (FDR+)
# EPHA2 (FDR+)
# CDKN1A (FDR+)
# ZNF397 (FDR-)
# ZNF547 (FDR-)
# RP11-156L14.1 (FDR-)
plotPercentBars(ca[startsWith(rownames(ca), "PDLIM4"),])
plotPercentBars(ca[startsWith(rownames(ca), "EPHA2"),])
plotPercentBars(ca[startsWith(rownames(ca), "CDKN1A"),])
plotPercentBars(ca[startsWith(rownames(ca), "ZNF397"),])
plotPercentBars(ca[startsWith(rownames(ca), "ZNF547"),])
plotPercentBars(ca[startsWith(rownames(ca), "RP11-156L14.1"),])

```

```{r}

#####################
# Top Genes PTSD DG #
#####################
# SNHG5 (nom+)
# STAM-AS1 (nom-)
plotPercentBars(dg[startsWith(rownames(dg), "FKBP5"),])
plotPercentBars(dg[startsWith(rownames(dg), "SNHG5"),])
plotPercentBars(dg[startsWith(rownames(dg), "STAM-AS1"),])

```

```{r}

####################
# Top Genes MDD DG #
####################
# CLU (FDR+)
# TMBIM6 (FDR+)
# UBE2H (FDR+)
# THBS3 (FDR-)
# ZNF814 (FDR-)
# MPPED2 (FDR-)
plotPercentBars(dg[startsWith(rownames(dg), "FKBP5"),])
plotPercentBars(dg[startsWith(rownames(dg), "SNHG5"),])
plotPercentBars(dg[startsWith(rownames(dg), "STAM-AS1"),])

```

```{r}

#######################
# Top Genes PTSD mPFC #
#######################
# STX11 (FDR+)
# RP11-413N10.3 (FDR-)
# CEBPB (FDR+)
# VASP (FDR+)
# STX3 (FDR-)
# SNX18P7 (FDR-)

plotPercentBars(mpfc[startsWith(rownames(mpfc), "FKBP5"),])
plotPercentBars(mpfc[startsWith(rownames(mpfc), "STX11"),])
plotPercentBars(mpfc[startsWith(rownames(mpfc), "RP11-413N10.3"),])
plotPercentBars(mpfc[startsWith(rownames(mpfc), "CEBPB"),])
plotPercentBars(mpfc[startsWith(rownames(mpfc), "VASP"),])
plotPercentBars(mpfc[startsWith(rownames(mpfc), "STX3"),])
plotPercentBars(mpfc[startsWith(rownames(mpfc), "SNX18P7"),])

```

```{r}

#######################
# Top Genes MDD mPFC #
#######################
# THBS3 (FDR-)
# CLU (FDR+)
# ZNF814 (FDR-)
# TMBIM6 (FDR+)
# MPPED2 (FDR-)
# UBE2H (FDR+)
plotPercentBars(mpfc[startsWith(rownames(mpfc), "THBS3"),])
plotPercentBars(mpfc[startsWith(rownames(mpfc), "CLU"),])
plotPercentBars(mpfc[startsWith(rownames(mpfc), "ZNF814"),])
plotPercentBars(mpfc[startsWith(rownames(mpfc), "TMBIM6"),])
plotPercentBars(mpfc[startsWith(rownames(mpfc), "MPPED2"),])
plotPercentBars(mpfc[startsWith(rownames(mpfc), "UBE2H"),])

```
